services:
  - type: web
    name: gen-iq-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: HF_API_KEY
        value: your_actual_huggingface_key_here
